version: '3.3'

services:

  wp-backend-node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    working_dir: /home/node/app
    restart: unless-stopped
    container_name: wp-backend-node
    ports:
      - "3000:3000"
    networks:
      default:
        ipv4_address: 172.27.0.10

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24